version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.sonatype.gradle.plugins.scan
    versions:
    - 2.0.4
    - 2.0.6
    - 2.0.7
    - 2.0.8
  - dependency-name: org.modelmapper:modelmapper
    versions:
    - 2.4.1
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - 7.5.4
    - 7.6.0
    - 7.7.0
    - 7.7.1
    - 7.7.3
    - 7.8.0
    - 7.8.1
  - dependency-name: com.diffplug.spotless
    versions:
    - 5.10.0
    - 5.10.2
    - 5.11.0
    - 5.11.1
    - 5.12.0
    - 5.12.1
  - dependency-name: com.sndyuk:logback-more-appenders
    versions:
    - 1.8.4-JAVA9MODULE_SLF4J17
    - 1.8.5-JAVA9MODULE_SLF4J17
  - dependency-name: org.owasp.dependencycheck
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.3
    - 6.1.4
  - dependency-name: com.github.spotbugs
    versions:
    - 4.6.1
    - 4.6.2
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.3
  - dependency-name: org.sonarqube
    versions:
    - 3.1.1
